server:
  port: 7001 #当前服务端口号

eureka:
  instance:
    hostname: eureka7001.com #hostname
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/ #其它节点地址



